// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: availability.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAvailability = `-- name: CreateAvailability :one
INSERT INTO availability (staff_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, staff_id, day_of_week, start_time, end_time, created_at
`

type CreateAvailabilityParams struct {
	StaffID   uuid.UUID   `db:"staff_id" json:"staff_id"`
	DayOfWeek int32       `db:"day_of_week" json:"day_of_week"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, createAvailability,
		arg.StaffID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const createOverride = `-- name: CreateOverride :one
INSERT INTO availability_overrides (staff_id, date, is_closed, start_time, end_time, reason)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, staff_id, date, is_closed, start_time, end_time, reason, created_at
`

type CreateOverrideParams struct {
	StaffID   uuid.UUID   `db:"staff_id" json:"staff_id"`
	Date      time.Time   `db:"date" json:"date"`
	IsClosed  bool        `db:"is_closed" json:"is_closed"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
	Reason    pgtype.Text `db:"reason" json:"reason"`
}

func (q *Queries) CreateOverride(ctx context.Context, arg CreateOverrideParams) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, createOverride,
		arg.StaffID,
		arg.Date,
		arg.IsClosed,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Date,
		&i.IsClosed,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAvailability = `-- name: DeleteAvailability :exec
DELETE FROM availability WHERE id = $1
`

func (q *Queries) DeleteAvailability(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailability, id)
	return err
}

const deleteAvailabilityByStaff = `-- name: DeleteAvailabilityByStaff :exec
DELETE FROM availability WHERE staff_id = $1
`

func (q *Queries) DeleteAvailabilityByStaff(ctx context.Context, staffID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAvailabilityByStaff, staffID)
	return err
}

const deleteOverride = `-- name: DeleteOverride :exec
DELETE FROM availability_overrides WHERE id = $1
`

func (q *Queries) DeleteOverride(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOverride, id)
	return err
}

const deleteOverrideByStaffAndDate = `-- name: DeleteOverrideByStaffAndDate :exec
DELETE FROM availability_overrides WHERE staff_id = $1 AND date = $2
`

type DeleteOverrideByStaffAndDateParams struct {
	StaffID uuid.UUID `db:"staff_id" json:"staff_id"`
	Date    time.Time `db:"date" json:"date"`
}

func (q *Queries) DeleteOverrideByStaffAndDate(ctx context.Context, arg DeleteOverrideByStaffAndDateParams) error {
	_, err := q.db.Exec(ctx, deleteOverrideByStaffAndDate, arg.StaffID, arg.Date)
	return err
}

const getAvailability = `-- name: GetAvailability :one
SELECT id, staff_id, day_of_week, start_time, end_time, created_at FROM availability
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetAvailability(ctx context.Context, id uuid.UUID) (Availability, error) {
	row := q.db.QueryRow(ctx, getAvailability, id)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const getOverride = `-- name: GetOverride :one
SELECT id, staff_id, date, is_closed, start_time, end_time, reason, created_at FROM availability_overrides
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetOverride(ctx context.Context, id uuid.UUID) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, getOverride, id)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Date,
		&i.IsClosed,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getOverrideByStaffAndDate = `-- name: GetOverrideByStaffAndDate :one
SELECT id, staff_id, date, is_closed, start_time, end_time, reason, created_at FROM availability_overrides
WHERE staff_id = $1 AND date = $2
LIMIT 1
`

type GetOverrideByStaffAndDateParams struct {
	StaffID uuid.UUID `db:"staff_id" json:"staff_id"`
	Date    time.Time `db:"date" json:"date"`
}

func (q *Queries) GetOverrideByStaffAndDate(ctx context.Context, arg GetOverrideByStaffAndDateParams) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, getOverrideByStaffAndDate, arg.StaffID, arg.Date)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Date,
		&i.IsClosed,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listAvailabilityByOrganization = `-- name: ListAvailabilityByOrganization :many
SELECT a.id, a.staff_id, a.day_of_week, a.start_time, a.end_time, a.created_at FROM availability a
JOIN staff s ON s.id = a.staff_id
WHERE s.organization_id = $1
ORDER BY s.name, a.day_of_week
`

func (q *Queries) ListAvailabilityByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Availability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAvailabilityByStaff = `-- name: ListAvailabilityByStaff :many
SELECT id, staff_id, day_of_week, start_time, end_time, created_at FROM availability
WHERE staff_id = $1
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) ListAvailabilityByStaff(ctx context.Context, staffID uuid.UUID) ([]Availability, error) {
	rows, err := q.db.Query(ctx, listAvailabilityByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Availability
	for rows.Next() {
		var i Availability
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesByStaff = `-- name: ListOverridesByStaff :many
SELECT id, staff_id, date, is_closed, start_time, end_time, reason, created_at FROM availability_overrides
WHERE staff_id = $1
ORDER BY date ASC
`

func (q *Queries) ListOverridesByStaff(ctx context.Context, staffID uuid.UUID) ([]AvailabilityOverride, error) {
	rows, err := q.db.Query(ctx, listOverridesByStaff, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityOverride
	for rows.Next() {
		var i AvailabilityOverride
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.Date,
			&i.IsClosed,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesByStaffAndRange = `-- name: ListOverridesByStaffAndRange :many
SELECT id, staff_id, date, is_closed, start_time, end_time, reason, created_at FROM availability_overrides
WHERE staff_id = $1
  AND date BETWEEN $2 AND $3
ORDER BY date ASC
`

type ListOverridesByStaffAndRangeParams struct {
	StaffID uuid.UUID `db:"staff_id" json:"staff_id"`
	Date    time.Time `db:"date" json:"date"`
	Date_2  time.Time `db:"date_2" json:"date_2"`
}

func (q *Queries) ListOverridesByStaffAndRange(ctx context.Context, arg ListOverridesByStaffAndRangeParams) ([]AvailabilityOverride, error) {
	rows, err := q.db.Query(ctx, listOverridesByStaffAndRange, arg.StaffID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AvailabilityOverride
	for rows.Next() {
		var i AvailabilityOverride
		if err := rows.Scan(
			&i.ID,
			&i.StaffID,
			&i.Date,
			&i.IsClosed,
			&i.StartTime,
			&i.EndTime,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAvailability = `-- name: UpdateAvailability :one
UPDATE availability SET
    day_of_week = $2,
    start_time = $3,
    end_time = $4
WHERE id = $1
RETURNING id, staff_id, day_of_week, start_time, end_time, created_at
`

type UpdateAvailabilityParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	DayOfWeek int32       `db:"day_of_week" json:"day_of_week"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
}

func (q *Queries) UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (Availability, error) {
	row := q.db.QueryRow(ctx, updateAvailability,
		arg.ID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i Availability
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
		&i.CreatedAt,
	)
	return i, err
}

const updateOverride = `-- name: UpdateOverride :one
UPDATE availability_overrides SET
    is_closed = $2,
    start_time = $3,
    end_time = $4,
    reason = $5
WHERE id = $1
RETURNING id, staff_id, date, is_closed, start_time, end_time, reason, created_at
`

type UpdateOverrideParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	IsClosed  bool        `db:"is_closed" json:"is_closed"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
	Reason    pgtype.Text `db:"reason" json:"reason"`
}

func (q *Queries) UpdateOverride(ctx context.Context, arg UpdateOverrideParams) (AvailabilityOverride, error) {
	row := q.db.QueryRow(ctx, updateOverride,
		arg.ID,
		arg.IsClosed,
		arg.StartTime,
		arg.EndTime,
		arg.Reason,
	)
	var i AvailabilityOverride
	err := row.Scan(
		&i.ID,
		&i.StaffID,
		&i.Date,
		&i.IsClosed,
		&i.StartTime,
		&i.EndTime,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}
