// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings SET
    status = 'CANCELLED',
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at
`

func (q *Queries) CancelBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countBookings = `-- name: CountBookings :one
SELECT COUNT(*) FROM bookings WHERE organization_id = $1
`

func (q *Queries) CountBookings(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBookings, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBookingsByStatus = `-- name: CountBookingsByStatus :many
SELECT status, COUNT(*)::bigint AS count
FROM bookings
WHERE organization_id = $1
GROUP BY status
`

type CountBookingsByStatusRow struct {
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) CountBookingsByStatus(ctx context.Context, organizationID uuid.UUID) ([]CountBookingsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countBookingsByStatus, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBookingsByStatusRow
	for rows.Next() {
		var i CountBookingsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (
    organization_id, service_id, staff_id, customer_id,
    customer_name, customer_email, customer_phone, notes,
    start_at, end_at, status, payment_status, stripe_session_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12, $13
) RETURNING id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at
`

type CreateBookingParams struct {
	OrganizationID  uuid.UUID   `db:"organization_id" json:"organization_id"`
	ServiceID       uuid.UUID   `db:"service_id" json:"service_id"`
	StaffID         uuid.UUID   `db:"staff_id" json:"staff_id"`
	CustomerID      pgtype.UUID `db:"customer_id" json:"customer_id"`
	CustomerName    string      `db:"customer_name" json:"customer_name"`
	CustomerEmail   string      `db:"customer_email" json:"customer_email"`
	CustomerPhone   pgtype.Text `db:"customer_phone" json:"customer_phone"`
	Notes           pgtype.Text `db:"notes" json:"notes"`
	StartAt         time.Time   `db:"start_at" json:"start_at"`
	EndAt           time.Time   `db:"end_at" json:"end_at"`
	Status          string      `db:"status" json:"status"`
	PaymentStatus   string      `db:"payment_status" json:"payment_status"`
	StripeSessionID pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.OrganizationID,
		arg.ServiceID,
		arg.StaffID,
		arg.CustomerID,
		arg.CustomerName,
		arg.CustomerEmail,
		arg.CustomerPhone,
		arg.Notes,
		arg.StartAt,
		arg.EndAt,
		arg.Status,
		arg.PaymentStatus,
		arg.StripeSessionID,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBooking, id)
	return err
}

const getBooking = `-- name: GetBooking :one
SELECT id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at FROM bookings
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, id uuid.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingByIDAndOrg = `-- name: GetBookingByIDAndOrg :one
SELECT id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at FROM bookings
WHERE id = $1 AND organization_id = $2
LIMIT 1
`

type GetBookingByIDAndOrgParams struct {
	ID             uuid.UUID `db:"id" json:"id"`
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
}

func (q *Queries) GetBookingByIDAndOrg(ctx context.Context, arg GetBookingByIDAndOrgParams) (Booking, error) {
	row := q.db.QueryRow(ctx, getBookingByIDAndOrg, arg.ID, arg.OrganizationID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBookings = `-- name: ListBookings :many
SELECT id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at FROM bookings
WHERE organization_id = $1
  AND ($2::timestamptz IS NULL OR start_at >= $2)
  AND ($3::timestamptz IS NULL OR start_at <= $3)
  AND ($4::text IS NULL OR status = $4)
  AND ($5::uuid IS NULL OR staff_id = $5)
ORDER BY start_at DESC
LIMIT $6 OFFSET $7
`

type ListBookingsParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Column2        time.Time `db:"column_2" json:"column_2"`
	Column3        time.Time `db:"column_3" json:"column_3"`
	Column4        string    `db:"column_4" json:"column_4"`
	Column5        uuid.UUID `db:"column_5" json:"column_5"`
	Limit          int32     `db:"limit" json:"limit"`
	Offset         int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookings,
		arg.OrganizationID,
		arg.Column2,
		arg.Column3,
		arg.Column4,
		arg.Column5,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.StaffID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Notes,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.PaymentStatus,
			&i.StripeSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByCustomerEmail = `-- name: ListBookingsByCustomerEmail :many
SELECT id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at FROM bookings
WHERE customer_email = $1
ORDER BY start_at DESC
`

func (q *Queries) ListBookingsByCustomerEmail(ctx context.Context, customerEmail string) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByCustomerEmail, customerEmail)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.StaffID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Notes,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.PaymentStatus,
			&i.StripeSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStaff = `-- name: ListBookingsByStaff :many
SELECT id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at FROM bookings
WHERE staff_id = $1
  AND ($2::timestamptz IS NULL OR start_at >= $2)
  AND ($3::timestamptz IS NULL OR start_at <= $3)
ORDER BY start_at ASC
`

type ListBookingsByStaffParams struct {
	StaffID uuid.UUID `db:"staff_id" json:"staff_id"`
	Column2 time.Time `db:"column_2" json:"column_2"`
	Column3 time.Time `db:"column_3" json:"column_3"`
}

func (q *Queries) ListBookingsByStaff(ctx context.Context, arg ListBookingsByStaffParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByStaff, arg.StaffID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.StaffID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Notes,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.PaymentStatus,
			&i.StripeSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverlappingBookings = `-- name: ListOverlappingBookings :many
SELECT id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at FROM bookings
WHERE staff_id = $1
  AND status IN ('PENDING','CONFIRMED')
  AND tstzrange(start_at, end_at) && tstzrange($2::timestamptz, $3::timestamptz)
`

type ListOverlappingBookingsParams struct {
	StaffID uuid.UUID `db:"staff_id" json:"staff_id"`
	Column2 time.Time `db:"column_2" json:"column_2"`
	Column3 time.Time `db:"column_3" json:"column_3"`
}

func (q *Queries) ListOverlappingBookings(ctx context.Context, arg ListOverlappingBookingsParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listOverlappingBookings, arg.StaffID, arg.Column2, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.StaffID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Notes,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.PaymentStatus,
			&i.StripeSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescheduleBooking = `-- name: RescheduleBooking :one
UPDATE bookings SET
    staff_id = $2,
    start_at = $3,
    end_at = $4,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at
`

type RescheduleBookingParams struct {
	ID      uuid.UUID `db:"id" json:"id"`
	StaffID uuid.UUID `db:"staff_id" json:"staff_id"`
	StartAt time.Time `db:"start_at" json:"start_at"`
	EndAt   time.Time `db:"end_at" json:"end_at"`
}

func (q *Queries) RescheduleBooking(ctx context.Context, arg RescheduleBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, rescheduleBooking,
		arg.ID,
		arg.StaffID,
		arg.StartAt,
		arg.EndAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingPaymentStatus = `-- name: UpdateBookingPaymentStatus :one
UPDATE bookings SET
    payment_status = $2,
    stripe_session_id = COALESCE($3, stripe_session_id),
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at
`

type UpdateBookingPaymentStatusParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	PaymentStatus   string      `db:"payment_status" json:"payment_status"`
	StripeSessionID pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
}

func (q *Queries) UpdateBookingPaymentStatus(ctx context.Context, arg UpdateBookingPaymentStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingPaymentStatus, arg.ID, arg.PaymentStatus, arg.StripeSessionID)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings SET
    status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, service_id, staff_id, customer_id, customer_name, customer_email, customer_phone, notes, start_at, end_at, status, payment_status, stripe_session_id, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID     uuid.UUID `db:"id" json:"id"`
	Status string    `db:"status" json:"status"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ServiceID,
		&i.StaffID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerEmail,
		&i.CustomerPhone,
		&i.Notes,
		&i.StartAt,
		&i.EndAt,
		&i.Status,
		&i.PaymentStatus,
		&i.StripeSessionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
