// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dashboard.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const dashboardBookingsByHour = `-- name: DashboardBookingsByHour :many
SELECT
    EXTRACT(HOUR FROM start_at)::int AS hour,
    COUNT(*)::bigint AS bookings_count
FROM bookings b
WHERE b.organization_id = $1
  AND b.start_at BETWEEN $2 AND $3
  AND b.status IN ('CONFIRMED','COMPLETED')
GROUP BY 1
ORDER BY 1 ASC
`

type DashboardBookingsByHourParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
}

type DashboardBookingsByHourRow struct {
	Hour          int32 `db:"hour" json:"hour"`
	BookingsCount int64 `db:"bookings_count" json:"bookings_count"`
}

func (q *Queries) DashboardBookingsByHour(ctx context.Context, arg DashboardBookingsByHourParams) ([]DashboardBookingsByHourRow, error) {
	rows, err := q.db.Query(ctx, dashboardBookingsByHour, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBookingsByHourRow
	for rows.Next() {
		var i DashboardBookingsByHourRow
		if err := rows.Scan(&i.Hour, &i.BookingsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardBookingsByStaff = `-- name: DashboardBookingsByStaff :many
SELECT
    st.id,
    st.name,
    COUNT(*)::bigint AS bookings_count,
    SUM(s.price_cents)::bigint AS revenue_cents
FROM bookings b
JOIN staff st ON st.id = b.staff_id
JOIN services s ON s.id = b.service_id
WHERE b.organization_id = $1
  AND b.start_at BETWEEN $2 AND $3
  AND b.status IN ('CONFIRMED','COMPLETED')
GROUP BY st.id, st.name
ORDER BY bookings_count DESC
`

type DashboardBookingsByStaffParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
}

type DashboardBookingsByStaffRow struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	BookingsCount int64     `db:"bookings_count" json:"bookings_count"`
	RevenueCents  int64     `db:"revenue_cents" json:"revenue_cents"`
}

func (q *Queries) DashboardBookingsByStaff(ctx context.Context, arg DashboardBookingsByStaffParams) ([]DashboardBookingsByStaffRow, error) {
	rows, err := q.db.Query(ctx, dashboardBookingsByStaff, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardBookingsByStaffRow
	for rows.Next() {
		var i DashboardBookingsByStaffRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BookingsCount,
			&i.RevenueCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardKPI = `-- name: DashboardKPI :one
SELECT
    COUNT(*)::bigint AS total_bookings,
    COUNT(*) FILTER (WHERE status IN ('CONFIRMED','COMPLETED'))::bigint AS confirmed_bookings,
    COUNT(*) FILTER (WHERE status = 'CANCELLED')::bigint AS cancelled_bookings,
    COALESCE(SUM(s.price_cents) FILTER (WHERE b.status IN ('CONFIRMED','COMPLETED')), 0)::bigint AS total_revenue_cents,
    COALESCE(AVG(s.price_cents) FILTER (WHERE b.status IN ('CONFIRMED','COMPLETED')), 0)::bigint AS avg_ticket_cents
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.organization_id = $1
  AND b.start_at BETWEEN $2 AND $3
`

type DashboardKPIParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
}

type DashboardKPIRow struct {
	TotalBookings     int64 `db:"total_bookings" json:"total_bookings"`
	ConfirmedBookings int64 `db:"confirmed_bookings" json:"confirmed_bookings"`
	CancelledBookings int64 `db:"cancelled_bookings" json:"cancelled_bookings"`
	TotalRevenueCents int64 `db:"total_revenue_cents" json:"total_revenue_cents"`
	AvgTicketCents    int64 `db:"avg_ticket_cents" json:"avg_ticket_cents"`
}

func (q *Queries) DashboardKPI(ctx context.Context, arg DashboardKPIParams) (DashboardKPIRow, error) {
	row := q.db.QueryRow(ctx, dashboardKPI, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	var i DashboardKPIRow
	err := row.Scan(
		&i.TotalBookings,
		&i.ConfirmedBookings,
		&i.CancelledBookings,
		&i.TotalRevenueCents,
		&i.AvgTicketCents,
	)
	return i, err
}

const dashboardOccupancy = `-- name: DashboardOccupancy :one
SELECT
    COUNT(*) FILTER (WHERE status IN ('CONFIRMED','COMPLETED'))::float / NULLIF(COUNT(*),0)::float * 100 AS occupancy_pct
FROM bookings
WHERE organization_id = $1
  AND start_at BETWEEN $2 AND $3
`

type DashboardOccupancyParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
}

func (q *Queries) DashboardOccupancy(ctx context.Context, arg DashboardOccupancyParams) (int32, error) {
	row := q.db.QueryRow(ctx, dashboardOccupancy, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	var occupancy_pct int32
	err := row.Scan(&occupancy_pct)
	return occupancy_pct, err
}

const dashboardRecentBookings = `-- name: DashboardRecentBookings :many
SELECT b.id, b.organization_id, b.service_id, b.staff_id, b.customer_id, b.customer_name, b.customer_email, b.customer_phone, b.notes, b.start_at, b.end_at, b.status, b.payment_status, b.stripe_session_id, b.created_at, b.updated_at, s.name AS service_name, st.name AS staff_name
FROM bookings b
JOIN services s ON s.id = b.service_id
JOIN staff st ON st.id = b.staff_id
WHERE b.organization_id = $1
ORDER BY b.created_at DESC
LIMIT $2
`

type DashboardRecentBookingsParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Limit          int32     `db:"limit" json:"limit"`
}

type DashboardRecentBookingsRow struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	OrganizationID  uuid.UUID   `db:"organization_id" json:"organization_id"`
	ServiceID       uuid.UUID   `db:"service_id" json:"service_id"`
	StaffID         uuid.UUID   `db:"staff_id" json:"staff_id"`
	CustomerID      pgtype.UUID `db:"customer_id" json:"customer_id"`
	CustomerName    string      `db:"customer_name" json:"customer_name"`
	CustomerEmail   string      `db:"customer_email" json:"customer_email"`
	CustomerPhone   pgtype.Text `db:"customer_phone" json:"customer_phone"`
	Notes           pgtype.Text `db:"notes" json:"notes"`
	StartAt         time.Time   `db:"start_at" json:"start_at"`
	EndAt           time.Time   `db:"end_at" json:"end_at"`
	Status          string      `db:"status" json:"status"`
	PaymentStatus   string      `db:"payment_status" json:"payment_status"`
	StripeSessionID pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
	ServiceName     string      `db:"service_name" json:"service_name"`
	StaffName       string      `db:"staff_name" json:"staff_name"`
}

func (q *Queries) DashboardRecentBookings(ctx context.Context, arg DashboardRecentBookingsParams) ([]DashboardRecentBookingsRow, error) {
	rows, err := q.db.Query(ctx, dashboardRecentBookings, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRecentBookingsRow
	for rows.Next() {
		var i DashboardRecentBookingsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ServiceID,
			&i.StaffID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerEmail,
			&i.CustomerPhone,
			&i.Notes,
			&i.StartAt,
			&i.EndAt,
			&i.Status,
			&i.PaymentStatus,
			&i.StripeSessionID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ServiceName,
			&i.StaffName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRevenueByDay = `-- name: DashboardRevenueByDay :many
SELECT
    date_trunc('day', start_at)::date AS day,
    SUM(s.price_cents)::bigint AS revenue_cents,
    COUNT(*)::bigint AS bookings_count
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.organization_id = $1
  AND b.status IN ('CONFIRMED','COMPLETED')
  AND b.start_at BETWEEN $2 AND $3
GROUP BY 1
ORDER BY 1 ASC
`

type DashboardRevenueByDayParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
}

type DashboardRevenueByDayRow struct {
	Day           time.Time `db:"day" json:"day"`
	RevenueCents  int64     `db:"revenue_cents" json:"revenue_cents"`
	BookingsCount int64     `db:"bookings_count" json:"bookings_count"`
}

func (q *Queries) DashboardRevenueByDay(ctx context.Context, arg DashboardRevenueByDayParams) ([]DashboardRevenueByDayRow, error) {
	rows, err := q.db.Query(ctx, dashboardRevenueByDay, arg.OrganizationID, arg.StartAt, arg.StartAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRevenueByDayRow
	for rows.Next() {
		var i DashboardRevenueByDayRow
		if err := rows.Scan(&i.Day, &i.RevenueCents, &i.BookingsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardRevenueByGranularity = `-- name: DashboardRevenueByGranularity :many
SELECT
    date_trunc($4::text, start_at) AS period,
    SUM(s.price_cents)::bigint AS revenue_cents,
    COUNT(*)::bigint AS bookings_count
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.organization_id = $1
  AND b.status IN ('CONFIRMED','COMPLETED')
  AND b.start_at BETWEEN $2 AND $3
GROUP BY 1
ORDER BY 1 ASC
`

type DashboardRevenueByGranularityParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
	Column4        string    `db:"column_4" json:"column_4"`
}

type DashboardRevenueByGranularityRow struct {
	Period        pgtype.Interval `db:"period" json:"period"`
	RevenueCents  int64           `db:"revenue_cents" json:"revenue_cents"`
	BookingsCount int64           `db:"bookings_count" json:"bookings_count"`
}

func (q *Queries) DashboardRevenueByGranularity(ctx context.Context, arg DashboardRevenueByGranularityParams) ([]DashboardRevenueByGranularityRow, error) {
	rows, err := q.db.Query(ctx, dashboardRevenueByGranularity,
		arg.OrganizationID,
		arg.StartAt,
		arg.StartAt_2,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardRevenueByGranularityRow
	for rows.Next() {
		var i DashboardRevenueByGranularityRow
		if err := rows.Scan(&i.Period, &i.RevenueCents, &i.BookingsCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopCustomers = `-- name: DashboardTopCustomers :many
SELECT
    b.customer_email,
    b.customer_name,
    COUNT(*)::bigint AS bookings_count,
    SUM(s.price_cents)::bigint AS total_spent_cents,
    MAX(b.start_at) AS last_booking_at
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.organization_id = $1
  AND b.status IN ('CONFIRMED','COMPLETED')
GROUP BY b.customer_email, b.customer_name
ORDER BY bookings_count DESC
LIMIT $2
`

type DashboardTopCustomersParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Limit          int32     `db:"limit" json:"limit"`
}

type DashboardTopCustomersRow struct {
	CustomerEmail   string      `db:"customer_email" json:"customer_email"`
	CustomerName    string      `db:"customer_name" json:"customer_name"`
	BookingsCount   int64       `db:"bookings_count" json:"bookings_count"`
	TotalSpentCents int64       `db:"total_spent_cents" json:"total_spent_cents"`
	LastBookingAt   interface{} `db:"last_booking_at" json:"last_booking_at"`
}

func (q *Queries) DashboardTopCustomers(ctx context.Context, arg DashboardTopCustomersParams) ([]DashboardTopCustomersRow, error) {
	rows, err := q.db.Query(ctx, dashboardTopCustomers, arg.OrganizationID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTopCustomersRow
	for rows.Next() {
		var i DashboardTopCustomersRow
		if err := rows.Scan(
			&i.CustomerEmail,
			&i.CustomerName,
			&i.BookingsCount,
			&i.TotalSpentCents,
			&i.LastBookingAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dashboardTopServices = `-- name: DashboardTopServices :many
SELECT
    s.id,
    s.name,
    s.color,
    COUNT(*)::bigint AS bookings_count,
    SUM(s.price_cents)::bigint AS revenue_cents
FROM bookings b
JOIN services s ON s.id = b.service_id
WHERE b.organization_id = $1
  AND b.start_at BETWEEN $2 AND $3
  AND b.status IN ('CONFIRMED','COMPLETED')
GROUP BY s.id, s.name, s.color
ORDER BY bookings_count DESC
LIMIT $4
`

type DashboardTopServicesParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	StartAt        time.Time `db:"start_at" json:"start_at"`
	StartAt_2      time.Time `db:"start_at_2" json:"start_at_2"`
	Limit          int32     `db:"limit" json:"limit"`
}

type DashboardTopServicesRow struct {
	ID            uuid.UUID `db:"id" json:"id"`
	Name          string    `db:"name" json:"name"`
	Color         string    `db:"color" json:"color"`
	BookingsCount int64     `db:"bookings_count" json:"bookings_count"`
	RevenueCents  int64     `db:"revenue_cents" json:"revenue_cents"`
}

func (q *Queries) DashboardTopServices(ctx context.Context, arg DashboardTopServicesParams) ([]DashboardTopServicesRow, error) {
	rows, err := q.db.Query(ctx, dashboardTopServices,
		arg.OrganizationID,
		arg.StartAt,
		arg.StartAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DashboardTopServicesRow
	for rows.Next() {
		var i DashboardTopServicesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.BookingsCount,
			&i.RevenueCents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
