// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Availability struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	StaffID   uuid.UUID   `db:"staff_id" json:"staff_id"`
	DayOfWeek int32       `db:"day_of_week" json:"day_of_week"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

type AvailabilityOverride struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	StaffID   uuid.UUID   `db:"staff_id" json:"staff_id"`
	Date      time.Time   `db:"date" json:"date"`
	IsClosed  bool        `db:"is_closed" json:"is_closed"`
	StartTime pgtype.Time `db:"start_time" json:"start_time"`
	EndTime   pgtype.Time `db:"end_time" json:"end_time"`
	Reason    pgtype.Text `db:"reason" json:"reason"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
}

type Booking struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	OrganizationID  uuid.UUID   `db:"organization_id" json:"organization_id"`
	ServiceID       uuid.UUID   `db:"service_id" json:"service_id"`
	StaffID         uuid.UUID   `db:"staff_id" json:"staff_id"`
	CustomerID      pgtype.UUID `db:"customer_id" json:"customer_id"`
	CustomerName    string      `db:"customer_name" json:"customer_name"`
	CustomerEmail   string      `db:"customer_email" json:"customer_email"`
	CustomerPhone   pgtype.Text `db:"customer_phone" json:"customer_phone"`
	Notes           pgtype.Text `db:"notes" json:"notes"`
	StartAt         time.Time   `db:"start_at" json:"start_at"`
	EndAt           time.Time   `db:"end_at" json:"end_at"`
	Status          string      `db:"status" json:"status"`
	PaymentStatus   string      `db:"payment_status" json:"payment_status"`
	StripeSessionID pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
}

type Customer struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
	Email          string      `db:"email" json:"email"`
	Name           string      `db:"name" json:"name"`
	Phone          pgtype.Text `db:"phone" json:"phone"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at" json:"updated_at"`
}

type Organization struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	Slug      string      `db:"slug" json:"slug"`
	Timezone  string      `db:"timezone" json:"timezone"`
	LogoUrl   pgtype.Text `db:"logo_url" json:"logo_url"`
	CreatedAt time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt time.Time   `db:"updated_at" json:"updated_at"`
}

type Payment struct {
	ID                    uuid.UUID   `db:"id" json:"id"`
	BookingID             uuid.UUID   `db:"booking_id" json:"booking_id"`
	OrganizationID        uuid.UUID   `db:"organization_id" json:"organization_id"`
	StripeEventID         pgtype.Text `db:"stripe_event_id" json:"stripe_event_id"`
	StripeSessionID       pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
	StripePaymentIntentID pgtype.Text `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	AmountCents           int32       `db:"amount_cents" json:"amount_cents"`
	Currency              string      `db:"currency" json:"currency"`
	Status                string      `db:"status" json:"status"`
	CreatedAt             time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time   `db:"updated_at" json:"updated_at"`
}

type RefreshToken struct {
	ID        uuid.UUID `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	TokenHash string    `db:"token_hash" json:"token_hash"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	Revoked   bool      `db:"revoked" json:"revoked"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type Service struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	OrganizationID  uuid.UUID   `db:"organization_id" json:"organization_id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	DurationMinutes int32       `db:"duration_minutes" json:"duration_minutes"`
	BufferMinutes   int32       `db:"buffer_minutes" json:"buffer_minutes"`
	PriceCents      int32       `db:"price_cents" json:"price_cents"`
	Color           string      `db:"color" json:"color"`
	IsActive        bool        `db:"is_active" json:"is_active"`
	CreatedAt       time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time   `db:"updated_at" json:"updated_at"`
}

type Staff struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	Name           string      `db:"name" json:"name"`
	Email          pgtype.Text `db:"email" json:"email"`
	AvatarUrl      pgtype.Text `db:"avatar_url" json:"avatar_url"`
	IsActive       bool        `db:"is_active" json:"is_active"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at" json:"updated_at"`
}

type StaffService struct {
	StaffID   uuid.UUID `db:"staff_id" json:"staff_id"`
	ServiceID uuid.UUID `db:"service_id" json:"service_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID             uuid.UUID   `db:"id" json:"id"`
	OrganizationID pgtype.UUID `db:"organization_id" json:"organization_id"`
	Email          string      `db:"email" json:"email"`
	PasswordHash   string      `db:"password_hash" json:"password_hash"`
	Name           string      `db:"name" json:"name"`
	Role           string      `db:"role" json:"role"`
	CreatedAt      time.Time   `db:"created_at" json:"created_at"`
	UpdatedAt      time.Time   `db:"updated_at" json:"updated_at"`
}
