// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPayments = `-- name: CountPayments :one
SELECT COUNT(*) FROM payments WHERE organization_id = $1
`

func (q *Queries) CountPayments(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPayments, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
    booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id,
    amount_cents, currency, status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
) RETURNING id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at
`

type CreatePaymentParams struct {
	BookingID             uuid.UUID   `db:"booking_id" json:"booking_id"`
	OrganizationID        uuid.UUID   `db:"organization_id" json:"organization_id"`
	StripeEventID         pgtype.Text `db:"stripe_event_id" json:"stripe_event_id"`
	StripeSessionID       pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
	StripePaymentIntentID pgtype.Text `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	AmountCents           int32       `db:"amount_cents" json:"amount_cents"`
	Currency              string      `db:"currency" json:"currency"`
	Status                string      `db:"status" json:"status"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.BookingID,
		arg.OrganizationID,
		arg.StripeEventID,
		arg.StripeSessionID,
		arg.StripePaymentIntentID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at FROM payments
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByBookingID = `-- name: GetPaymentByBookingID :one
SELECT id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at FROM payments
WHERE booking_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByBookingID(ctx context.Context, bookingID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBookingID, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByStripeEventID = `-- name: GetPaymentByStripeEventID :one
SELECT id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at FROM payments
WHERE stripe_event_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByStripeEventID(ctx context.Context, stripeEventID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByStripeEventID, stripeEventID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByStripeSessionID = `-- name: GetPaymentByStripeSessionID :one
SELECT id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at FROM payments
WHERE stripe_session_id = $1
LIMIT 1
`

func (q *Queries) GetPaymentByStripeSessionID(ctx context.Context, stripeSessionID pgtype.Text) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByStripeSessionID, stripeSessionID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByOrganization = `-- name: ListPaymentsByOrganization :many
SELECT id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at FROM payments
WHERE organization_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByOrganizationParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Limit          int32     `db:"limit" json:"limit"`
	Offset         int32     `db:"offset" json:"offset"`
}

func (q *Queries) ListPaymentsByOrganization(ctx context.Context, arg ListPaymentsByOrganizationParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByOrganization, arg.OrganizationID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.BookingID,
			&i.OrganizationID,
			&i.StripeEventID,
			&i.StripeSessionID,
			&i.StripePaymentIntentID,
			&i.AmountCents,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePaymentByStripeEvent = `-- name: UpdatePaymentByStripeEvent :one
UPDATE payments SET
    status = $2,
    updated_at = now()
WHERE stripe_event_id = $1
RETURNING id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at
`

type UpdatePaymentByStripeEventParams struct {
	StripeEventID pgtype.Text `db:"stripe_event_id" json:"stripe_event_id"`
	Status        string      `db:"status" json:"status"`
}

func (q *Queries) UpdatePaymentByStripeEvent(ctx context.Context, arg UpdatePaymentByStripeEventParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentByStripeEvent, arg.StripeEventID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments SET
    status = $2,
    stripe_payment_intent_id = COALESCE($3, stripe_payment_intent_id),
    updated_at = now()
WHERE id = $1
RETURNING id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID                    uuid.UUID   `db:"id" json:"id"`
	Status                string      `db:"status" json:"status"`
	StripePaymentIntentID pgtype.Text `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.StripePaymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPaymentByStripeEvent = `-- name: UpsertPaymentByStripeEvent :one
INSERT INTO payments (
    booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id,
    amount_cents, currency, status
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8
) ON CONFLICT (stripe_event_id) DO UPDATE SET
    status = EXCLUDED.status,
    stripe_payment_intent_id = COALESCE(EXCLUDED.stripe_payment_intent_id, payments.stripe_payment_intent_id),
    updated_at = now()
RETURNING id, booking_id, organization_id, stripe_event_id, stripe_session_id, stripe_payment_intent_id, amount_cents, currency, status, created_at, updated_at
`

type UpsertPaymentByStripeEventParams struct {
	BookingID             uuid.UUID   `db:"booking_id" json:"booking_id"`
	OrganizationID        uuid.UUID   `db:"organization_id" json:"organization_id"`
	StripeEventID         pgtype.Text `db:"stripe_event_id" json:"stripe_event_id"`
	StripeSessionID       pgtype.Text `db:"stripe_session_id" json:"stripe_session_id"`
	StripePaymentIntentID pgtype.Text `db:"stripe_payment_intent_id" json:"stripe_payment_intent_id"`
	AmountCents           int32       `db:"amount_cents" json:"amount_cents"`
	Currency              string      `db:"currency" json:"currency"`
	Status                string      `db:"status" json:"status"`
}

func (q *Queries) UpsertPaymentByStripeEvent(ctx context.Context, arg UpsertPaymentByStripeEventParams) (Payment, error) {
	row := q.db.QueryRow(ctx, upsertPaymentByStripeEvent,
		arg.BookingID,
		arg.OrganizationID,
		arg.StripeEventID,
		arg.StripeSessionID,
		arg.StripePaymentIntentID,
		arg.AmountCents,
		arg.Currency,
		arg.Status,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.OrganizationID,
		&i.StripeEventID,
		&i.StripeSessionID,
		&i.StripePaymentIntentID,
		&i.AmountCents,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
