// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddStaffService(ctx context.Context, arg AddStaffServiceParams) error
	CancelBooking(ctx context.Context, id uuid.UUID) (Booking, error)
	CountBookings(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountBookingsByStatus(ctx context.Context, organizationID uuid.UUID) ([]CountBookingsByStatusRow, error)
	CountPayments(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountServices(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CountStaff(ctx context.Context, organizationID uuid.UUID) (int64, error)
	CreateAvailability(ctx context.Context, arg CreateAvailabilityParams) (Availability, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) (Organization, error)
	CreateOverride(ctx context.Context, arg CreateOverrideParams) (AvailabilityOverride, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DashboardBookingsByHour(ctx context.Context, arg DashboardBookingsByHourParams) ([]DashboardBookingsByHourRow, error)
	DashboardBookingsByStaff(ctx context.Context, arg DashboardBookingsByStaffParams) ([]DashboardBookingsByStaffRow, error)
	DashboardBusiestMonth(ctx context.Context, arg DashboardBusiestMonthParams) (DashboardBusiestMonthRow, error)
	DashboardCancelRate(ctx context.Context, arg DashboardCancelRateParams) (int32, error)
	DashboardHeatmap(ctx context.Context, arg DashboardHeatmapParams) ([]DashboardHeatmapRow, error)
	DashboardKPI(ctx context.Context, arg DashboardKPIParams) (DashboardKPIRow, error)
	DashboardOccupancy(ctx context.Context, arg DashboardOccupancyParams) (int32, error)
	DashboardRecentBookings(ctx context.Context, arg DashboardRecentBookingsParams) ([]DashboardRecentBookingsRow, error)
	// Dashboard aggregates — 5 row (PLAN.md T06) — all queries use DATE_TRUNC + GROUP BY in DB with index on start_at (idx_bookings_start_at, idx_bookings_org_status_time), not JS.
	// Store UTC (timestamptz), render in organization.timezone (Asia/Jakarta default). Availability engine uses tstzrange for overlap; dashboard uses BETWEEN + DATE_TRUNC for aggregates.
	// Staff scoping: OWNER full, STAFF filtered via optional staff_id param — pass '00000000-0000-0000-0000-000000000000'::uuid for no filter (OWNER), or real staff_id for STAFF.
	// All date ranges use BETWEEN with B-tree index on start_at; grouping via DATE_TRUNC uses hash aggregation in DB, not JS.
	DashboardRevenueByDay(ctx context.Context, arg DashboardRevenueByDayParams) ([]DashboardRevenueByDayRow, error)
	DashboardRevenueByGranularity(ctx context.Context, arg DashboardRevenueByGranularityParams) ([]DashboardRevenueByGranularityRow, error)
	DashboardRevenueByGranularityTZ(ctx context.Context, arg DashboardRevenueByGranularityTZParams) ([]DashboardRevenueByGranularityTZRow, error)
	DashboardTopCustomers(ctx context.Context, arg DashboardTopCustomersParams) ([]DashboardTopCustomersRow, error)
	DashboardTopServices(ctx context.Context, arg DashboardTopServicesParams) ([]DashboardTopServicesRow, error)
	DeleteAvailability(ctx context.Context, id uuid.UUID) error
	DeleteAvailabilityByStaff(ctx context.Context, staffID uuid.UUID) error
	DeleteBooking(ctx context.Context, id uuid.UUID) error
	DeleteExpiredRefreshTokens(ctx context.Context) error
	DeleteOverride(ctx context.Context, id uuid.UUID) error
	DeleteOverrideByStaffAndDate(ctx context.Context, arg DeleteOverrideByStaffAndDateParams) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteStaff(ctx context.Context, id uuid.UUID) error
	GetAvailability(ctx context.Context, id uuid.UUID) (Availability, error)
	GetBooking(ctx context.Context, id uuid.UUID) (Booking, error)
	GetBookingByIDAndOrg(ctx context.Context, arg GetBookingByIDAndOrgParams) (Booking, error)
	GetCustomerByEmail(ctx context.Context, arg GetCustomerByEmailParams) (Customer, error)
	GetOrganizationByID(ctx context.Context, id uuid.UUID) (Organization, error)
	GetOrganizationBySlug(ctx context.Context, slug string) (Organization, error)
	GetOverride(ctx context.Context, id uuid.UUID) (AvailabilityOverride, error)
	GetOverrideByStaffAndDate(ctx context.Context, arg GetOverrideByStaffAndDateParams) (AvailabilityOverride, error)
	GetPayment(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByBookingID(ctx context.Context, bookingID uuid.UUID) (Payment, error)
	GetPaymentByStripeEventID(ctx context.Context, stripeEventID pgtype.Text) (Payment, error)
	GetPaymentByStripeSessionID(ctx context.Context, stripeSessionID pgtype.Text) (Payment, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetService(ctx context.Context, id uuid.UUID) (Service, error)
	GetServiceByName(ctx context.Context, arg GetServiceByNameParams) (Service, error)
	GetStaff(ctx context.Context, id uuid.UUID) (Staff, error)
	GetStaffByEmail(ctx context.Context, arg GetStaffByEmailParams) (Staff, error)
	GetStaffByUserID(ctx context.Context, userID pgtype.UUID) (Staff, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	ListAvailabilityByOrganization(ctx context.Context, organizationID uuid.UUID) ([]Availability, error)
	ListAvailabilityByStaff(ctx context.Context, staffID uuid.UUID) ([]Availability, error)
	ListBookings(ctx context.Context, arg ListBookingsParams) ([]Booking, error)
	ListBookingsByCustomerEmail(ctx context.Context, customerEmail string) ([]Booking, error)
	ListBookingsByStaff(ctx context.Context, arg ListBookingsByStaffParams) ([]Booking, error)
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListOverlappingBookings(ctx context.Context, arg ListOverlappingBookingsParams) ([]Booking, error)
	ListOverridesByStaff(ctx context.Context, staffID uuid.UUID) ([]AvailabilityOverride, error)
	ListOverridesByStaffAndRange(ctx context.Context, arg ListOverridesByStaffAndRangeParams) ([]AvailabilityOverride, error)
	ListPaymentsByOrganization(ctx context.Context, arg ListPaymentsByOrganizationParams) ([]Payment, error)
	ListRefreshTokensByUser(ctx context.Context, userID uuid.UUID) ([]RefreshToken, error)
	ListServices(ctx context.Context, organizationID uuid.UUID) ([]Service, error)
	ListServicesAll(ctx context.Context, organizationID uuid.UUID) ([]Service, error)
	ListStaff(ctx context.Context, organizationID uuid.UUID) ([]Staff, error)
	ListStaffAll(ctx context.Context, organizationID uuid.UUID) ([]Staff, error)
	ListStaffByService(ctx context.Context, serviceID uuid.UUID) ([]Staff, error)
	ListStaffServices(ctx context.Context, staffID uuid.UUID) ([]StaffService, error)
	ListUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]User, error)
	RemoveStaffService(ctx context.Context, arg RemoveStaffServiceParams) error
	RescheduleBooking(ctx context.Context, arg RescheduleBookingParams) (Booking, error)
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetStaffServices(ctx context.Context, staffID uuid.UUID) error
	UpdateAvailability(ctx context.Context, arg UpdateAvailabilityParams) (Availability, error)
	UpdateBookingPaymentStatus(ctx context.Context, arg UpdateBookingPaymentStatusParams) (Booking, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdateOverride(ctx context.Context, arg UpdateOverrideParams) (AvailabilityOverride, error)
	UpdatePaymentByStripeEvent(ctx context.Context, arg UpdatePaymentByStripeEventParams) (Payment, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertCustomer(ctx context.Context, arg UpsertCustomerParams) (Customer, error)
	UpsertPaymentByStripeEvent(ctx context.Context, arg UpsertPaymentByStripeEventParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
