// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: services.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countServices = `-- name: CountServices :one
SELECT COUNT(*) FROM services WHERE organization_id = $1
`

func (q *Queries) CountServices(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countServices, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (
    organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	OrganizationID  uuid.UUID   `db:"organization_id" json:"organization_id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	DurationMinutes int32       `db:"duration_minutes" json:"duration_minutes"`
	BufferMinutes   int32       `db:"buffer_minutes" json:"buffer_minutes"`
	PriceCents      int32       `db:"price_cents" json:"price_cents"`
	Color           string      `db:"color" json:"color"`
	IsActive        bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.OrganizationID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.PriceCents,
		arg.Color,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.PriceCents,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active, created_at, updated_at FROM services
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetService(ctx context.Context, id uuid.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.PriceCents,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServiceByName = `-- name: GetServiceByName :one
SELECT id, organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active, created_at, updated_at FROM services
WHERE organization_id = $1 AND name = $2
LIMIT 1
`

type GetServiceByNameParams struct {
	OrganizationID uuid.UUID `db:"organization_id" json:"organization_id"`
	Name           string    `db:"name" json:"name"`
}

func (q *Queries) GetServiceByName(ctx context.Context, arg GetServiceByNameParams) (Service, error) {
	row := q.db.QueryRow(ctx, getServiceByName, arg.OrganizationID, arg.Name)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.PriceCents,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active, created_at, updated_at FROM services
WHERE organization_id = $1
  AND is_active = true
ORDER BY name ASC
`

func (q *Queries) ListServices(ctx context.Context, organizationID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.PriceCents,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServicesAll = `-- name: ListServicesAll :many
SELECT id, organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active, created_at, updated_at FROM services
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListServicesAll(ctx context.Context, organizationID uuid.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServicesAll, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.BufferMinutes,
			&i.PriceCents,
			&i.Color,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services SET
    name = $2,
    description = $3,
    duration_minutes = $4,
    buffer_minutes = $5,
    price_cents = $6,
    color = $7,
    is_active = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, name, description, duration_minutes, buffer_minutes, price_cents, color, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	ID              uuid.UUID   `db:"id" json:"id"`
	Name            string      `db:"name" json:"name"`
	Description     pgtype.Text `db:"description" json:"description"`
	DurationMinutes int32       `db:"duration_minutes" json:"duration_minutes"`
	BufferMinutes   int32       `db:"buffer_minutes" json:"buffer_minutes"`
	PriceCents      int32       `db:"price_cents" json:"price_cents"`
	Color           string      `db:"color" json:"color"`
	IsActive        bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.BufferMinutes,
		arg.PriceCents,
		arg.Color,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.BufferMinutes,
		&i.PriceCents,
		&i.Color,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
