// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: staff.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addStaffService = `-- name: AddStaffService :exec
INSERT INTO staff_services (staff_id, service_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddStaffServiceParams struct {
	StaffID   uuid.UUID `db:"staff_id" json:"staff_id"`
	ServiceID uuid.UUID `db:"service_id" json:"service_id"`
}

func (q *Queries) AddStaffService(ctx context.Context, arg AddStaffServiceParams) error {
	_, err := q.db.Exec(ctx, addStaffService, arg.StaffID, arg.ServiceID)
	return err
}

const countStaff = `-- name: CountStaff :one
SELECT COUNT(*) FROM staff WHERE organization_id = $1
`

func (q *Queries) CountStaff(ctx context.Context, organizationID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countStaff, organizationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStaff = `-- name: CreateStaff :one
INSERT INTO staff (
    organization_id, user_id, name, email, avatar_url, is_active
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at
`

type CreateStaffParams struct {
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
	UserID         pgtype.UUID `db:"user_id" json:"user_id"`
	Name           string      `db:"name" json:"name"`
	Email          pgtype.Text `db:"email" json:"email"`
	AvatarUrl      pgtype.Text `db:"avatar_url" json:"avatar_url"`
	IsActive       bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) CreateStaff(ctx context.Context, arg CreateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, createStaff,
		arg.OrganizationID,
		arg.UserID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.IsActive,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStaff = `-- name: DeleteStaff :exec
DELETE FROM staff WHERE id = $1
`

func (q *Queries) DeleteStaff(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaff, id)
	return err
}

const getStaff = `-- name: GetStaff :one
SELECT id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at FROM staff
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetStaff(ctx context.Context, id uuid.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaff, id)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByEmail = `-- name: GetStaffByEmail :one
SELECT id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at FROM staff
WHERE organization_id = $1 AND email = $2
LIMIT 1
`

type GetStaffByEmailParams struct {
	OrganizationID uuid.UUID   `db:"organization_id" json:"organization_id"`
	Email          pgtype.Text `db:"email" json:"email"`
}

func (q *Queries) GetStaffByEmail(ctx context.Context, arg GetStaffByEmailParams) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByEmail, arg.OrganizationID, arg.Email)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStaffByUserID = `-- name: GetStaffByUserID :one
SELECT id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at FROM staff
WHERE user_id = $1
LIMIT 1
`

func (q *Queries) GetStaffByUserID(ctx context.Context, userID pgtype.UUID) (Staff, error) {
	row := q.db.QueryRow(ctx, getStaffByUserID, userID)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStaff = `-- name: ListStaff :many
SELECT id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at FROM staff
WHERE organization_id = $1
  AND is_active = true
ORDER BY name ASC
`

func (q *Queries) ListStaff(ctx context.Context, organizationID uuid.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaff, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffAll = `-- name: ListStaffAll :many
SELECT id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at FROM staff
WHERE organization_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListStaffAll(ctx context.Context, organizationID uuid.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffAll, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffByService = `-- name: ListStaffByService :many
SELECT s.id, s.organization_id, s.user_id, s.name, s.email, s.avatar_url, s.is_active, s.created_at, s.updated_at FROM staff s
JOIN staff_services ss ON ss.staff_id = s.id
WHERE ss.service_id = $1
  AND s.is_active = true
ORDER BY s.name ASC
`

func (q *Queries) ListStaffByService(ctx context.Context, serviceID uuid.UUID) ([]Staff, error) {
	rows, err := q.db.Query(ctx, listStaffByService, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Staff
	for rows.Next() {
		var i Staff
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.AvatarUrl,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffServices = `-- name: ListStaffServices :many
SELECT staff_id, service_id, created_at FROM staff_services
WHERE staff_id = $1
`

func (q *Queries) ListStaffServices(ctx context.Context, staffID uuid.UUID) ([]StaffService, error) {
	rows, err := q.db.Query(ctx, listStaffServices, staffID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaffService
	for rows.Next() {
		var i StaffService
		if err := rows.Scan(&i.StaffID, &i.ServiceID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStaffService = `-- name: RemoveStaffService :exec
DELETE FROM staff_services
WHERE staff_id = $1 AND service_id = $2
`

type RemoveStaffServiceParams struct {
	StaffID   uuid.UUID `db:"staff_id" json:"staff_id"`
	ServiceID uuid.UUID `db:"service_id" json:"service_id"`
}

func (q *Queries) RemoveStaffService(ctx context.Context, arg RemoveStaffServiceParams) error {
	_, err := q.db.Exec(ctx, removeStaffService, arg.StaffID, arg.ServiceID)
	return err
}

const setStaffServices = `-- name: SetStaffServices :exec
DELETE FROM staff_services WHERE staff_id = $1
`

func (q *Queries) SetStaffServices(ctx context.Context, staffID uuid.UUID) error {
	_, err := q.db.Exec(ctx, setStaffServices, staffID)
	return err
}

const updateStaff = `-- name: UpdateStaff :one
UPDATE staff SET
    name = $2,
    email = $3,
    avatar_url = $4,
    is_active = $5,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, user_id, name, email, avatar_url, is_active, created_at, updated_at
`

type UpdateStaffParams struct {
	ID        uuid.UUID   `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	Email     pgtype.Text `db:"email" json:"email"`
	AvatarUrl pgtype.Text `db:"avatar_url" json:"avatar_url"`
	IsActive  bool        `db:"is_active" json:"is_active"`
}

func (q *Queries) UpdateStaff(ctx context.Context, arg UpdateStaffParams) (Staff, error) {
	row := q.db.QueryRow(ctx, updateStaff,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.IsActive,
	)
	var i Staff
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.UserID,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
